### ISSUE TITLE
Relevant experience for your first data science co-op job.

### ISSUE THREAD

**Issue by colinmarsch** [jxnl/ama#6]
I was just wondering what kind of previous experience you had at the time you got your first data science related co-op job? What do you think would be a good level to reach skill-wise before trying for data science positions?

**Comment by jxnl** [comment]
My first Data Science Internship was my second internship. At that point, I had taken the Andrew Ng Machine Learning course, written 2-3 side projects (primarily demos of algorithms in Python), and was familiar with spark and some big data tools. 

My benchmark is always whether I could write a blog post on the topic and explain what I've learned.

I wrote an [answer on Quora](https://www.quora.com/I-see-lots-of-people-asking-how-to-become-a-data-scientist-but-what-is-a-realistic-timeframe-for-getting-a-full-time-job-starting-from-ground-zero/answer/Jason-Liu-21) about my experience starting out as a data science internship.

This post was a while ago when  Waterloo/coop didn't really see data science as popular as it was now. I think now, basic stats plus programming skills is enough to apply. Since everyone's in school the ability to learn stats is something that I think everyone has. Taking the time out of work to get the basics of R/tidyverse or Python/Scipy/Pandas before you get started will really help you out. On the same token, you'll definitely exponentially grow your technical skills once you get the job.
